[package]
name = "bl_lexer"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
derive_more = { workspace = true }

bl_ast = { workspace = true }
bl_workspace = { workspace = true }
bl_reporting = { workspace = true }

num-derive = { workspace = true }
num-traits = { workspace = true }
phf = { workspace = true }
strum_macros = { workspace = true }
thin-vec = { workspace = true }
