[package]
name = "bl_utils"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
codespan-reporting = "0.11.1"
log = { workspace = true }
once_cell = { workspace = true }
path-absolutize = { workspace = true}
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
