

[package]
name = "bl_tests"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "bl-tests"
path = "./lib.rs"
doctest = false

[dependencies]
pretty_assertions = "1.4.1"
regex = { workspace = true }
lazy_static = "1.5.0"
log = { workspace = true }

bl_lints = { workspace = true }
bl_reporting = { workspace = true }
bl_utils = { workspace = true }
bl_workspace = { workspace = true }
bracketlint = { path = "../crates/bl" }

# Internal macros the that the tester uses
bl_testing_macros = { path = "./testing-macros" }
bl_testing_internal = { path = "./testing-internal" }

[dev-dependencies]
clap = { workspace = true}
rusty-fork = "0.3"
