[package]
name = "bl_parse"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
bitflags = { workspace = true}
crossbeam-channel = { workspace = true }
derive_more = { workspace = true }
log = { workspace = true }
thin-vec = { workspace = true }

bl_ast = { workspace = true }
bl_lexer = { workspace = true }
bl_reporting = { workspace = true }
bl_workspace = { workspace = true }
